name: "Request"
description: "Submit a request to the RDK Tiger Team."
projects: ["rdkcentral/68"]
title: "Request: <Short summary of the request>"
body:
- type: textarea
  attributes:
    label: "Request"
    placeholder: "What is the request?"
  id: request
  validations:
    required: true
